language: ruby
sudo: false

rvm:
  - 2.1
  - 2.2
  - 2.3
  - 3.0

gemfile:
  - gemfiles/rails_4_2.gemfile

services:
  - mysql

before_script:
  - mysql -e 'create database ar_transaction_changes_test'
